<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $foods = [[
            // start menu carnival
            'picture' => 'carnival6.jpeg',
            'nama_menu' => 'French Fries',
            'deskripsi' => 'Kentang goreng dengan bumbu dan saos pilihan',
            'harga' => 16000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival5.jpg',
            'nama_menu' => 'Mushroom Crispy Jumbo',
            'deskripsi' => 'Jamur goreng dengan bumbu dan saos pilihan',
            'harga' => 14000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival8.jpg',
            'nama_menu' => 'Tahu Crispy',
            'deskripsi' => 'Tahu goreng dengan bumbu dan saos pilihan',
            'harga' => 12000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival7.jpg',
            'nama_menu' => 'Kulit Ayam Crispy',
            'deskripsi' => 'Kulit ayam crispy ditaburi bumbu pilihan',
            'harga' => 14000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival4.jpg',
            'nama_menu' => 'Curly Fries',
            'deskripsi' => 'Kentang curly dengan bumbu dan saos pilihan',
            'harga' => 16000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival3.jpg',
            'nama_menu' => 'Chicken Crispy',
            'deskripsi' => 'Potongan ayam goreng crispy ditaburi bumbu lezat',
            'harga' => 17000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival1.jpg',
            'nama_menu' => 'Fish Ball',
            'deskripsi' => 'Bola ikan, isi 10',
            'harga' => 16000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival2.jpg',
            'nama_menu' => 'Shrimp Ball',
            'deskripsi' => 'Bola udang, isi 8',
            'harga' => 16000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
            // end menu carnival
        ],     [
            // start menu japanesefood
            'picture' => 'japanesefood1.jpg',
            'nama_menu' => 'Nasi Goreng Original',
            'deskripsi' => 'Nasi goreng dengan bumbu original',
            'harga' => 18000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood2.jpg',
            'nama_menu' => 'Nasi Goreng Hongkong',
            'deskripsi' => 'Nasi goreng ala Hongkong',
            'harga' => 20000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood3.jpg',
            'nama_menu' => 'Teriyaki',
            'deskripsi' => 'Ayam atau daging panggang dengan saus teriyaki',
            'harga' => 25000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood4.jpg',
            'nama_menu' => 'Yakiniku',
            'deskripsi' => 'Daging panggang ala Jepang',
            'harga' => 28000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood5.jpg',
            'nama_menu' => 'Yakisoba',
            'deskripsi' => 'Mie panggang dengan sayuran dan daging',
            'harga' => 22000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood6.jpeg',
            'nama_menu' => 'Chicken Katsu',
            'deskripsi' => 'Ayam goreng tepung khas Jepang',
            'harga' => 20000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood7.jpg',
            'nama_menu' => 'Beef Bowl',
            'deskripsi' => 'Donburi dengan daging sapi',
            'harga' => 23000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'japanesefood8.jpg',
            'nama_menu' => 'Sushi',
            'deskripsi' => 'Seleksi sushi yang lezat',
            'harga' => 30000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'japanesefood9.jpg',
            'nama_menu' => 'Ramen',
            'deskripsi' => 'Mie Jepang dalam kuah lezat',
            'harga' => 25000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'japanesefood10.jpg',
            'nama_menu' => 'Chicken Karaage',
            'deskripsi' => 'Ayam goreng ala Jepang',
            'harga' => 22000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
            // end japanese food
        ],
        [
            //start depot kita
            'picture' => 'depotkita1.jpg',
            'nama_menu' => 'Nasi Ayam Goreng',
            'deskripsi' => 'Nasi dengan ayam goreng spesial',
            'harga' => 18000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita2.jpg',
            'nama_menu' => 'Nasi Fu Yung Hai',
            'deskripsi' => 'Nasi dengan telur fu yung hai',
            'harga' => 22000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita3.jpg',
            'nama_menu' => 'Nasi Koloke',
            'deskripsi' => 'Nasi dengan campuran kol dan bakso',
            'harga' => 20000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita4.jpg',
            'nama_menu' => 'Nasi Campur',
            'deskripsi' => 'Nasi dengan berbagai macam lauk',
            'harga' => 25000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita5.jpg',
            'nama_menu' => 'Nasi Ayam Geprek',
            'deskripsi' => 'Nasi dengan ayam geprek yang pedas',
            'harga' => 21000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita6.jpg',
            'nama_menu' => 'Es Soda Gembira',
            'deskripsi' => 'Minuman segar dengan soda dan sirup',
            'harga' => 8000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita8.jpg',
            'nama_menu' => 'Milo',
            'deskripsi' => 'Minuman coklat bubuk Milo',
            'harga' => 10000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
            // end depot kita
        ],
        [
            // start depot mapan
            'picture' => 'depotmapan1.jpg',
            'nama_menu' => 'Nasi Goreng Telur',
            'deskripsi' => 'Nasi goreng dengan telur',
            'harga' => 15000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan2.jpg',
            'nama_menu' => 'Nasi Campur',
            'deskripsi' => 'Nasi dengan berbagai macam lauk',
            'harga' => 18000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan3.jpg',
            'nama_menu' => 'Nasi Ayam Koloke',
            'deskripsi' => 'Nasi dengan ayam dan koloke',
            'harga' => 20000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan4.jpg',
            'nama_menu' => 'Nasi Capcay',
            'deskripsi' => 'Nasi dengan campuran sayuran dan daging',
            'harga' => 22000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan5.jpg',
            'nama_menu' => 'Es Teh',
            'deskripsi' => 'Minuman teh dingin',
            'harga' => 5000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan6.jpg',
            'nama_menu' => 'Es Jeruk',
            'deskripsi' => 'Minuman jeruk segar',
            'harga' => 6000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
            //end depot mapan
        ],
        [
            //start kuenyonya
            'picture' => 'kuenyonya1.jpg',
            'nama_menu' => 'Lemper',
            'deskripsi' => '4pcs Makanan tradisional berisi ketan dan daging',
            'harga' => 12000,
            'toko_id' => 'kuenyonya@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kuenyonya2.jpg',
            'nama_menu' => 'Kue Nyonya',
            'deskripsi' => '2pcs Kue tradisional khas Nyonya',
            'harga' => 10000,
            'toko_id' => 'kuenyonya@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kuenyonya3.jpg',
            'nama_menu' => 'Kue Ambon',
            'deskripsi' => '3pcs Kue tradisional khas Ambon',
            'harga' => 15000,
            'toko_id' => 'kuenyonya@gmail.com',
            'kantin_id' => 3,
            //end kuenyonya
        ],
        [
            // start sotoayamjago
            'picture' => 'sotoayamjago1.jpg',
            'nama_menu' => 'Soto Ayam Telur',
            'deskripsi' => 'Soto ayam dengan tambahan telur',
            'harga' => 12000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago2.jpg',
            'nama_menu' => 'Soto Ayam Spesial',
            'deskripsi' => 'Soto ayam spesial dengan bumbu istimewa',
            'harga' => 15000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago3.jpeg',
            'nama_menu' => 'Soto Ayam Jago',
            'deskripsi' => 'Soto ayam khas dengan cita rasa yang unik',
            'harga' => 18000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago4.jpg',
            'nama_menu' => 'Soto Ayam',
            'deskripsi' => 'Soto ayam dengan kuah yang lezat',
            'harga' => 13000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago5.jpg',
            'nama_menu' => 'Soto Ayam Campur',
            'deskripsi' => 'Soto ayam dengan campuran berbagai bahan',
            'harga' => 16000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago6.jpg',
            'nama_menu' => 'Nasi Putih',
            'deskripsi' => 'Nasi putih yang lembut',
            'harga' => 5000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago7.jpg',
            'nama_menu' => 'Lontong',
            'deskripsi' => 'Lontong sebagai pelengkap hidangan',
            'harga' => 3000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago8.jpg',
            'nama_menu' => 'Es Teh Manis',
            'deskripsi' => 'Minuman teh manis yang segar',
            'harga' => 6000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
            // end soto ayam jago
        ],
        [
            // start ndokee
            'picture' => 'ndokee1.jpeg',
            'nama_menu' => 'Nasi Goreng Ayam',
            'deskripsi' => 'Nasi goreng dengan potongan ayam yang lezat',
            'harga' => 12000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee2.jpg',
            'nama_menu' => 'Nasi Koloke',
            'deskripsi' => 'Nasi dengan campuran daging dan sayuran',
            'harga' => 10000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee3.jpg',
            'nama_menu' => 'Ayam Lada Hitam',
            'deskripsi' => 'Ayam dengan saus lada hitam yang pedas',
            'harga' => 15000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee4.jpg',
            'nama_menu' => 'Fu Yung Hai',
            'deskripsi' => 'Telur dadar dengan berbagai bahan',
            'harga' => 8000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee5.jpg',
            'nama_menu' => 'Telur Kornet',
            'deskripsi' => 'Telur dengan kornet yang gurih',
            'harga' => 9000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee6.jpeg',
            'nama_menu' => 'Cap Jay',
            'deskripsi' => 'Sayuran dengan campuran daging',
            'harga' => 11000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee7.jpg',
            'nama_menu' => 'Ayam Jamur',
            'deskripsi' => 'Ayam dengan saus jamur yang lezat',
            'harga' => 13000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee8.jpg',
            'nama_menu' => 'Bakmie Goreng Ayam',
            'deskripsi' => 'Mie goreng dengan potongan ayam',
            'harga' => 14000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
            // end ndokee
        ],
        [
            'picture' => 'kedaihong1.jpg',
            'nama_menu' => 'Nasi Ayam Kremus',
            'deskripsi' => 'Nasi dengan ayam bumbu kremus yang lezat',
            'harga' => 16000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'kedaihong2.jpg',
            'nama_menu' => 'Nasi Ayam Bakar',
            'deskripsi' => 'Nasi dengan ayam bakar yang harum',
            'harga' => 18000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'kedaihong3.jpg',
            'nama_menu' => 'Nasi Ayam Bumbu Rujak',
            'deskripsi' => 'Nasi dengan ayam bumbu rujak yang segar',
            'harga' => 15000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'kedaihong4.jpg',
            'nama_menu' => 'Nasi Ayam Penyet',
            'deskripsi' => 'Nasi dengan ayam penyet yang pedas',
            'harga' => 17000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'kedaihong5.jpeg',
            'nama_menu' => 'Tahu Tek',
            'deskripsi' => 'Tahu dengan saus kacang khas Tahu Tek',
            'harga' => 12000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'kedaihong6.jpg',
            'nama_menu' => 'Indomie',
            'deskripsi' => 'Mie instan dengan berbagai pilihan rasa',
            'harga' => 8000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'kedaihong7.jpg',
            'nama_menu' => 'Es Teh',
            'deskripsi' => 'Minuman teh manis yang segar',
            'harga' => 5000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'kedaihong8.jpeg',
            'nama_menu' => 'Es Jeruk',
            'deskripsi' => 'Minuman jeruk segar',
            'harga' => 6000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'kedaihong9.jpg',
            'nama_menu' => 'Cappucino',
            'deskripsi' => 'Kopi dengan foam susu lembut',
            'harga' => 10000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 1,
             // end hong
        ],
        [
            'picture' => 'depotmie551.jpg',
            'nama_menu' => 'Pangsit Kuah',
            'deskripsi' => 'Pangsit dengan kuah yang lezat',
            'harga' => 12000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'depotmie552.jpg',
            'nama_menu' => 'Mie Bakso',
            'deskripsi' => 'Mie dengan bakso yang kenyal',
            'harga' => 15000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'depotmie553.jpeg',
            'nama_menu' => 'Mie Goreng Jamur',
            'deskripsi' => 'Mie goreng dengan jamur yang lezat',
            'harga' => 13000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'depotmie554.jpg',
            'nama_menu' => 'Mie Goreng Special',
            'deskripsi' => 'Mie goreng dengan berbagai bahan spesial',
            'harga' => 16000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'depotmie555.jpg',
            'nama_menu' => 'Mie Cap Jay Goreng/Kuah',
            'deskripsi' => 'Mie Cap Jay goreng atau dengan kuah',
            'harga' => 14000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'depotmie556.jpg',
            'nama_menu' => 'Ayam Penyet',
            'deskripsi' => 'Ayam penyet dengan sambal pedas',
            'harga' => 17000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'depotmie557.jpg',
            'nama_menu' => 'Ayam Bakar',
            'deskripsi' => 'Ayam bakar dengan bumbu khas',
            'harga' => 18000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'depotmie558.jpeg',
            'nama_menu' => 'Telor Ceplok',
            'deskripsi' => 'Telur ceplok dengan bumbu',
            'harga' => 8000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'depotmie559.jpg',
            'nama_menu' => 'Sate Ayam',
            'deskripsi' => 'Sate ayam dengan bumbu kacang',
            'harga' => 12000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'depotmie5510.jpg',
            'nama_menu' => 'Sate Kambing',
            'deskripsi' => 'Sate kambing dengan bumbu kacang',
            'harga' => 15000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 1,
        ],
        // end depot mie
        [
            'picture' => 'ayampinarak1.jpg',
            'nama_menu' => 'Ayam Broiler Utuh',
            'deskripsi' => 'Ayam broiler utuh dengan bumbu khas',
            'harga' => 80000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'ayampinarak2.jpeg',
            'nama_menu' => 'Ayam Kampung Utuh',
            'deskripsi' => 'Ayam kampung utuh dengan bumbu tradisional',
            'harga' => 60000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'ayampinarak3.jpg',
            'nama_menu' => 'Jamur Crispy',
            'deskripsi' => 'Jamur crispy dengan tepung renyah',
            'harga' => 12000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'ayampinarak4.jpg',
            'nama_menu' => 'Tahu Crispy',
            'deskripsi' => 'Tahu crispy dengan tepung renyah',
            'harga' => 10000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'ayampinarak5.jpg',
            'nama_menu' => 'Tahu Tempe',
            'deskripsi' => 'Tahu dan tempe goreng dengan bumbu kacang',
            'harga' => 15000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 1,
        ],
        // end pinarak
        [
            'picture' => 'pokpok1.jpg',
            'nama_menu' => 'Chicken Popcorn',
            'deskripsi' => 'Potongan ayam kecil yang digoreng garing',
            'harga' => 12000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'pokpok2.jpg',
            'nama_menu' => 'Chicken Skin',
            'deskripsi' => 'Kulit ayam yang digoreng crispy',
            'harga' => 10000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'pokpok3.jpg',
            'nama_menu' => 'Crispy Dory',
            'deskripsi' => 'Daging dory yang digoreng dengan tepung renyah',
            'harga' => 18000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'pokpok4.jpg',
            'nama_menu' => 'Crispy Squid',
            'deskripsi' => 'Cumi-cumi yang digoreng dengan tepung crispy',
            'harga' => 15000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'pokpok5.jpg',
            'nama_menu' => 'Tofu Fries',
            'deskripsi' => 'Tahu yang dipotong seperti kentang goreng',
            'harga' => 13000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'pokpok6.jpg',
            'nama_menu' => 'French Fries',
            'deskripsi' => 'Kentang goreng dengan bentuk panjang',
            'harga' => 10000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 1,
        ],
        // end pokpok
        
        [
            'picture' => 'chattime1.jpg',
            'nama_menu' => 'Milk Tea',
            'deskripsi' => 'Minuman teh susu yang lezat',
            'harga' => 12000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime2.jpg',
            'nama_menu' => 'Vanilla Milk Tea',
            'deskripsi' => 'Minuman teh susu dengan rasa vanilla',
            'harga' => 13000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime3.jpg',
            'nama_menu' => 'Hazelnut Milk Tea',
            'deskripsi' => 'Minuman teh susu dengan rasa hazelnut',
            'harga' => 14000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime4.jpg',
            'nama_menu' => 'Mango Green Tea',
            'deskripsi' => 'Minuman mangga hijau dengan aroma melati',
            'harga' => 11000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime5.jpg',
            'nama_menu' => 'Green Tea Latte',
            'deskripsi' => 'Minuman susu dengan teh hijau',
            'harga' => 15000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime6.jpg',
            'nama_menu' => 'Kopi Susu Gula Aren',
            'deskripsi' => 'Kopi dengan susu dan gula aren',
            'harga' => 16000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime7.jpg',
            'nama_menu' => 'Mochacinno',
            'deskripsi' => 'Kopi dengan campuran coklat dan susu',
            'harga' => 17000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime8.jpg',
            'nama_menu' => 'Americano',
            'deskripsi' => 'Kopi hitam tanpa susu',
            'harga' => 10000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime9.jpg',
            'nama_menu' => 'Latte',
            'deskripsi' => 'Espresso dengan susu',
            'harga' => 12000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime10.jpg',
            'nama_menu' => 'Cappuccino',
            'deskripsi' => 'Kopi dengan foam susu lembut',
            'harga' => 14000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime11.jpg',
            'nama_menu' => 'Vanilla Latte',
            'deskripsi' => 'Latte dengan rasa vanilla',
            'harga' => 16000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime12.jpg',
            'nama_menu' => 'Hazelnut Latte',
            'deskripsi' => 'Latte dengan rasa hazelnut',
            'harga' => 16000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime13.jpg',
            'nama_menu' => 'Caramel Latte',
            'deskripsi' => 'Latte dengan rasa karamel',
            'harga' => 17000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime14.jpg',
            'nama_menu' => 'Pure Cocoa',
            'deskripsi' => 'Minuman coklat murni tanpa tambahan susu',
            'harga' => 13000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'chattime15.jpg',
            'nama_menu' => 'Honey Lemon Juice',
            'deskripsi' => 'Minuman lemon dengan tambahan madu',
            'harga' => 12000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 1,
        ],
        // end chattime
        [
            'picture' => 'starbucks1.jpg',
            'nama_menu' => 'Caramel Macchiato',
            'deskripsi' => 'Espresso dengan susu dan sirup karamel',
            'harga' => 28000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'starbucks2.jpg',
            'nama_menu' => 'Americano',
            'deskripsi' => 'Kopi hitam tanpa susu',
            'harga' => 24000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'starbucks3.jpg',
            'nama_menu' => 'Caffe Mocha',
            'deskripsi' => 'Espresso dengan susu dan saus coklat',
            'harga' => 26000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'starbucks4.jpg',
            'nama_menu' => 'Green Tea Latte',
            'deskripsi' => 'Minuman susu dengan teh hijau',
            'harga' => 25000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'starbucks5.jpg',
            'nama_menu' => 'Matcha Latte',
            'deskripsi' => 'Minuman susu dengan bubuk matcha',
            'harga' => 27000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'starbucks6.jpg',
            'nama_menu' => 'Chocolate Signature',
            'deskripsi' => 'Minuman coklat spesial dengan rasa khas',
            'harga' => 29000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'starbucks7.jpg',
            'nama_menu' => 'Peppermint Mocha',
            'deskripsi' => 'Caffe Mocha dengan rasa mint segar',
            'harga' => 30000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 1,
        ],
        [
            'picture' => 'starbucks8.jpg',
            'nama_menu' => 'Sakura Latte',
            'deskripsi' => 'Minuman susu dengan aroma sakura',
            'harga' => 28000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 1,
            // end starbucks
        ],
        [
            'picture' => 'mieremaja1.png',
            'nama_menu' => 'Bakmie Goreng / Kuah',
            'deskripsi' => 'Mie goreng atau mie kuah pilihan dengan bumbu spesial',
            'harga' => 25000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'mieremaja2.png',
            'nama_menu' => 'Bakmie Special',
            'deskripsi' => 'Mie spesial dengan campuran bahan-bahan istimewa',
            'harga' => 30000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'mieremaja3.jpeg',
            'nama_menu' => 'Bihun Goreng / Kuah',
            'deskripsi' => 'Bihun goreng atau bihun kuah dengan rasa lezat',
            'harga' => 22000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'mieremaja4.jpg',
            'nama_menu' => 'Kwetiau Goreng',
            'deskripsi' => 'Kwetiau goreng dengan bumbu khas',
            'harga' => 28000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'mieremaja5.jpg',
            'nama_menu' => 'Kwetiau Goreng Seafood',
            'deskripsi' => 'Kwetiau goreng seafood dengan bumbu khas',
            'harga' => 28000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'mieremaja6.jpg',
            'nama_menu' => 'Nasi Goreng Mawut',
            'deskripsi' => 'Nasi goreng dengan campuran berbagai bahan mawut',
            'harga' => 32000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'mieremaja7.jpeg',
            'nama_menu' => 'Nasi Goreng Ikan Asin',
            'deskripsi' => 'Nasi goreng dengan cita rasa ikan asin yang khas',
            'harga' => 35000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'mieremaja8.jpg',
            'nama_menu' => 'Nasi Goreng Hong Kong',
            'deskripsi' => 'Nasi goreng versi Hong Kong dengan bumbu istimewa',
            'harga' => 38000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'mieremaja9.jpg',
            'nama_menu' => 'Nasi Cap Jay',
            'deskripsi' => 'Nasi goreng dengan campuran sayuran khas Cap Jay',
            'harga' => 30000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'mieremaja10.jpg',
            'nama_menu' => 'Fu Yung Hai',
            'deskripsi' => 'Menu spesial dengan telur dan bahan-bahan istimewa',
            'harga' => 25000,
            'toko_id' => 'mieremaja@gmail.com',
            'kantin_id' => 4,
            // end mieremaja
        ],
        [
            'picture' => 'kopte1.png',
            'nama_menu' => 'Kopte Tarik Kopte',
            'deskripsi' => 'Menu kopte tarik kopte dengan cita rasa unik',
            'harga' => 28000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte2.png',
            'nama_menu' => 'Teh Tarik Cincau',
            'deskripsi' => 'Minuman teh tarik dengan tambahan cincau',
            'harga' => 15000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte3.png',
            'nama_menu' => 'Teh Tarik Kopte',
            'deskripsi' => 'Minuman teh tarik ala Kopte dengan rasa khas',
            'harga' => 18000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte4.png',
            'nama_menu' => 'Coklat Tarik',
            'deskripsi' => 'Minuman coklat dengan tampilan tarik yang unik',
            'harga' => 20000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte5.png',
            'nama_menu' => 'Teh Jeruk Nipis',
            'deskripsi' => 'Minuman teh dengan tambahan jeruk nipis segar',
            'harga' => 12000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte6.png',
            'nama_menu' => 'Teh Kundur',
            'deskripsi' => 'Minuman teh dengan rasa kundur yang unik',
            'harga' => 16000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte7.png',
            'nama_menu' => 'Milo Dinosaur',
            'deskripsi' => 'Minuman Milo dengan hiasan dan topping istimewa',
            'harga' => 22000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte8.png',
            'nama_menu' => 'Teh Tarik Panas',
            'deskripsi' => 'Minuman teh tarik dengan suhu panas',
            'harga' => 16000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte9.png',
            'nama_menu' => 'Toast Kaya Butter',
            'deskripsi' => 'Roti panggang dengan selai kaya dan mentega',
            'harga' => 25000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte10.png',
            'nama_menu' => 'Toast Choco Peanut',
            'deskripsi' => 'Roti panggang dengan campuran coklat dan kacang',
            'harga' => 27000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte11.png',
            'nama_menu' => 'Toast Peanut',
            'deskripsi' => 'Roti panggang dengan topping kacang',
            'harga' => 23000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kopte12.png',
            'nama_menu' => 'Toast Chocolate',
            'deskripsi' => 'Roti panggang dengan saus coklat',
            'harga' => 26000,
            'toko_id' => 'kopte@gmail.com',
            'kantin_id' => 4,
            // END KOPTE 
        ],
        [
            'picture' => 'sambalapi1.jpg',
            'nama_menu' => 'Nasi Ayam Bakar',
            'deskripsi' => 'Nasi dengan ayam yang dibakar dengan bumbu khas',
            'harga' => 28000,
            'toko_id' => 'sambalapi@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'sambalapi2.jpg',
            'nama_menu' => 'Nasi Ayam Goreng',
            'deskripsi' => 'Nasi dengan ayam yang digoreng dengan renyah',
            'harga' => 25000,
            'toko_id' => 'sambalapi@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'sambalapi3.jpeg',
            'nama_menu' => 'Nasi Bebek Bakar',
            'deskripsi' => 'Nasi dengan bebek yang dibakar dengan cita rasa istimewa',
            'harga' => 32000,
            'toko_id' => 'sambalapi@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'sambalapi4.jpg',
            'nama_menu' => 'Nasi Bebek Goreng',
            'deskripsi' => 'Nasi dengan bebek yang digoreng dengan kelezatan yang luar biasa',
            'harga' => 30000,
            'toko_id' => 'sambalapi@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'sambalapi5.jpg',
            'nama_menu' => 'Nasi Bandeng Bakar',
            'deskripsi' => 'Nasi dengan bandeng yang dibakar dengan bumbu spesial',
            'harga' => 35000,
            'toko_id' => 'sambalapi@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'sambalapi6.jpg',
            'nama_menu' => 'Nasi Bandeng Goreng',
            'deskripsi' => 'Nasi dengan bandeng yang digoreng dengan kelezatan tinggi',
            'harga' => 33000,
            'toko_id' => 'sambalapi@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'sambalapi7.jpg',
            'nama_menu' => 'Nasi Ikan Cakalang',
            'deskripsi' => 'Nasi dengan ikan cakalang yang lezat',
            'harga' => 30000,
            'toko_id' => 'sambalapi@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'sambalapi8.jpg',
            'nama_menu' => 'Nasi Ayam Geprek',
            'deskripsi' => 'Nasi dengan ayam yang di geprek dengan sambal pedas',
            'harga' => 27000,
            'toko_id' => 'sambalapi@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'sambalapi9.jpg',
            'nama_menu' => 'Nasi Goreng Telur',
            'deskripsi' => 'Nasi goreng dengan tambahan telur',
            'harga' => 25000,
            'toko_id' => 'sambalapi@gmail.com',
            'kantin_id' => 4,
            // end sambal api
        ],
        [
            'picture' => 'kxkresto1.png',
            'nama_menu' => 'Chicken Eggstra',
            'deskripsi' => 'Ayam dengan telur sebagai tambahan ekstra',
            'harga' => 28000,
            'toko_id' => 'kxkresto@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kxkresto2.png',
            'nama_menu' => 'Tenderloin Eggstra',
            'deskripsi' => 'Daging tenderloin dengan telur sebagai tambahan ekstra',
            'harga' => 32000,
            'toko_id' => 'kxkresto@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kxkresto3.png',
            'nama_menu' => 'Beef Slice',
            'deskripsi' => 'Potongan daging sapi dengan bumbu spesial',
            'harga' => 35000,
            'toko_id' => 'kxkresto@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kxkresto4.png',
            'nama_menu' => 'Kulit Crispy',
            'deskripsi' => 'Kulit ayam yang digoreng hingga crispy',
            'harga' => 25000,
            'toko_id' => 'kxkresto@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kxkresto5.png',
            'nama_menu' => 'Chicken Leg',
            'deskripsi' => 'Paha ayam goreng dengan cita rasa khas',
            'harga' => 30000,
            'toko_id' => 'kxkresto@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'kxkresto6.png',
            'nama_menu' => 'Beef Sosis',
            'deskripsi' => 'Sosis daging sapi dengan rasa yang lezat',
            'harga' => 28000,
            'toko_id' => 'kxkresto@gmail.com',
            'kantin_id' => 4,
            // end kxk
        ],
        [
            'picture' => 'excelso1.jpg',
            'nama_menu' => 'Cookies and Cream',
            'deskripsi' => 'Minuman atau makanan penutup dengan rasa cookies and cream',
            'harga' => 25000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso2.jpg',
            'nama_menu' => 'Choco Chip',
            'deskripsi' => 'Minuman atau makanan penutup dengan tambahan choco chip',
            'harga' => 27000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso3.jpg',
            'nama_menu' => 'Caramel Jelly',
            'deskripsi' => 'Minuman atau makanan penutup dengan rasa karamel dan jelly',
            'harga' => 30000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso4.jpg',
            'nama_menu' => 'Iced Coffee',
            'deskripsi' => 'Minuman kopi dingin dengan rasa yang menyegarkan',
            'harga' => 28000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso5.png',
            'nama_menu' => 'Lychee Tea',
            'deskripsi' => 'Minuman teh dengan tambahan buah lychee',
            'harga' => 25000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso6.jpg',
            'nama_menu' => 'Matcha Pearl',
            'deskripsi' => 'Minuman atau makanan penutup dengan rasa matcha dan pearl',
            'harga' => 32000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso7.png',
            'nama_menu' => 'Love Story',
            'deskripsi' => 'Minuman atau makanan penutup dengan cerita cinta',
            'harga' => 35000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso8.png',
            'nama_menu' => 'Peach Tea',
            'deskripsi' => 'Minuman teh dengan tambahan buah peach',
            'harga' => 30000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso9.jpg',
            'nama_menu' => 'Thai Tea Pearl',
            'deskripsi' => 'Minuman atau makanan penutup dengan rasa teh Thailand dan pearl',
            'harga' => 32000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso10.jpg',
            'nama_menu' => 'Banana Split',
            'deskripsi' => 'Makanan penutup dengan campuran pisang dan es krim',
            'harga' => 35000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso11.jpg',
            'nama_menu' => 'Mocha',
            'deskripsi' => 'Minuman kopi dengan rasa mocha yang lezat',
            'harga' => 26000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso12.jpg',
            'nama_menu' => 'Mocha Jelly Shake',
            'deskripsi' => 'Minuman shake dengan kombinasi mocha dan jelly',
            'harga' => 32000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
        ],
        [
            'picture' => 'excelso13.jpg',
            'nama_menu' => 'Mega Mocha Shake',
            'deskripsi' => 'Minuman shake dengan ukuran mega dan rasa mocha',
            'harga' => 38000,
            'toko_id' => 'excelso@gmail.com',
            'kantin_id' => 4,
            // end excelso
        ],
        [
            'picture' => 'dcrepes1.png',
            'nama_menu' => 'Beef Burger',
            'deskripsi' => 'Crepes topping burger dengan daging sapi yang lezat',
            'harga' => 35000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'dcrepes2.png',
            'nama_menu' => 'Pepperoni Pizza',
            'deskripsi' => 'Crepes dengan topping pepperoni yang khas',
            'harga' => 40000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'dcrepes3.png',
            'nama_menu' => 'Chilli Doc',
            'deskripsi' => 'Crepes dengan campuran cabai yang pedas',
            'harga' => 32000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'dcrepes4.png',
            'nama_menu' => 'Crispy Chicken BBQ',
            'deskripsi' => 'Crepes Ayam crispy dengan saus BBQ yang lezat',
            'harga' => 38000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'dcrepes5.png',
            'nama_menu' => 'Steak & Cheese',
            'deskripsi' => 'Crepes steak dengan keju sebagai pelengkap',
            'harga' => 45000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'dcrepes6.png',
            'nama_menu' => 'Smoked Beef & Cheese',
            'deskripsi' => 'Crepes daging asap dengan keju sebagai pelengkap',
            'harga' => 42000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'dcrepes7.png',
            'nama_menu' => 'Spicy Tuna',
            'deskripsi' => 'Crepes tuna dengan saus pedas sebagai tambahan',
            'harga' => 38000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'dcrepes8.png',
            'nama_menu' => 'Tuna Pizza',
            'deskripsi' => 'Crepes dengan topping tuna pizza yang lezat',
            'harga' => 42000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'dcrepes9.png',
            'nama_menu' => 'Choco Cheese',
            'deskripsi' => 'Crepes dengan kombinasi coklat dan keju',
            'harga' => 30000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'dcrepes10.png',
            'nama_menu' => 'Banana Choco Cheese',
            'deskripsi' => 'Crepes dengan pisang, coklat, dan keju',
            'harga' => 35000,
            'toko_id' => 'dcrepes@gmail.com',
            'kantin_id' => 2,
            //end dcrepes

        ],
        [
            'picture' => 'baksosapiasli1.jpg',
            'nama_menu' => 'Bakso Mercon',
            'deskripsi' => 'Bakso dengan cita rasa pedas mercon yang unik',
            'harga' => 25000,
            'toko_id' => 'baksosapiasli@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'baksosapiasli2.jpg',
            'nama_menu' => 'Bakso Campur',
            'deskripsi' => 'Bakso campur dengan berbagai macam tambahan',
            'harga' => 28000,
            'toko_id' => 'baksosapiasli@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'baksosapiasli3.jpg',
            'nama_menu' => 'Bakso Sapi',
            'deskripsi' => 'Bakso dengan daging sapi yang lembut',
            'harga' => 30000,
            'toko_id' => 'baksosapiasli@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'baksosapiasli4.jpg',
            'nama_menu' => 'Bakso Sapi Urat',
            'deskripsi' => 'Bakso dengan daging sapi urat yang kenyal',
            'harga' => 32000,
            'toko_id' => 'baksosapiasli@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'baksosapiasli5.jpg',
            'nama_menu' => 'Bakso Telur',
            'deskripsi' => 'Bakso dengan tambahan telur rebus',
            'harga' => 26000,
            'toko_id' => 'baksosapiasli@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'baksosapiasli6.jpg',
            'nama_menu' => 'Es Teh',
            'deskripsi' => 'Minuman teh dingin yang menyegarkan',
            'harga' => 5000,
            'toko_id' => 'baksosapiasli@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'baksosapiasli7.jpg',
            'nama_menu' => 'Es Jeruk',
            'deskripsi' => 'Minuman jeruk dingin yang segar',
            'harga' => 7000,
            'toko_id' => 'baksosapiasli@gmail.com',
            'kantin_id' => 2,
            // end bakso sapi asli
        ],
        [
            'picture' => 'markittop1.jpeg',
            'nama_menu' => 'Nasi Goreng Jawa',
            'deskripsi' => 'Nasi goreng dengan bumbu khas Jawa',
            'harga' => 25000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'markittop2.jpg',
            'nama_menu' => 'Nasi Goreng Ikan Asin',
            'deskripsi' => 'Nasi goreng dengan tambahan ikan asin yang gurih',
            'harga' => 28000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'markittop3.jpg',
            'nama_menu' => 'Nasi Goreng Mawut',
            'deskripsi' => 'Nasi goreng dengan campuran berbagai bahan',
            'harga' => 30000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'markittop4.jpg',
            'nama_menu' => 'Nasi Goreng Cumi',
            'deskripsi' => 'Nasi goreng dengan tambahan cumi yang lezat',
            'harga' => 32000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'markittop5.jpg',
            'nama_menu' => 'Nasi Krengsengan',
            'deskripsi' => 'Nasi dengan krengsengan yang khas',
            'harga' => 28000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'markittop6.jpg',
            'nama_menu' => 'Nasi Koloke',
            'deskripsi' => 'Nasi dengan koloke sebagai tambahan',
            'harga' => 30000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'markittop7.jpg',
            'nama_menu' => 'Nasi Fu Yung Hai',
            'deskripsi' => 'Nasi dengan hidangan Fu Yung Hai yang lezat',
            'harga' => 32000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'markittop8.jpg',
            'nama_menu' => 'Nasi Capjay',
            'deskripsi' => 'Nasi dengan campuran sayuran ala Capjay',
            'harga' => 30000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'markittop9.jpg',
            'nama_menu' => 'Mie Goreng Jawa',
            'deskripsi' => 'Mie goreng dengan bumbu khas Jawa',
            'harga' => 25000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'markittop10.jpg',
            'nama_menu' => 'Bakmie Goreng',
            'deskripsi' => 'Bakmie goreng dengan berbagai tambahan',
            'harga' => 28000,
            'toko_id' => 'markittop@gmail.com',
            'kantin_id' => 2,
            //end markittop
        ],
        [
            'picture' => 'berkatkatering1.jpg',
            'nama_menu' => 'Nasi Kuning',
            'deskripsi' => 'Nasi kuning dengan bumbu khas yang lezat',
            'harga' => 20000,
            'toko_id' => 'berkatkatering@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'berkatkatering2.jpg',
            'nama_menu' => 'Nasi Uduk',
            'deskripsi' => 'Nasi uduk dengan pelengkap yang lezat',
            'harga' => 18000,
            'toko_id' => 'berkatkatering@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'berkatkatering3.jpg',
            'nama_menu' => 'Nasi Empal',
            'deskripsi' => 'Nasi dengan empal yang lembut dan gurih',
            'harga' => 25000,
            'toko_id' => 'berkatkatering@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'berkatkatering4.jpg',
            'nama_menu' => 'Nasi Rawon',
            'deskripsi' => 'Nasi dengan kuah rawon yang khas',
            'harga' => 28000,
            'toko_id' => 'berkatkatering@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'berkatkatering5.jpg',
            'nama_menu' => 'Nasi Soto Daging',
            'deskripsi' => 'Nasi dengan kuah soto daging yang lezat',
            'harga' => 23000,
            'toko_id' => 'berkatkatering@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'berkatkatering6.jpeg',
            'nama_menu' => 'Nasi Pecel',
            'deskripsi' => 'Nasi dengan sambal pecel dan sayuran segar',
            'harga' => 22000,
            'toko_id' => 'berkatkatering@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'berkatkatering7.jpg',
            'nama_menu' => 'Nasi Timbel Ayam',
            'deskripsi' => 'Nasi timbel dengan ayam sebagai lauk',
            'harga' => 25000,
            'toko_id' => 'berkatkatering@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'berkatkatering8.jpg',
            'nama_menu' => 'Nasi Timbel Empal',
            'deskripsi' => 'Nasi timbel dengan empal sebagai lauk',
            'harga' => 26000,
            'toko_id' => 'berkatkatering@gmail.com',
            'kantin_id' => 2,
        ],
        [
            'picture' => 'berkatkatering9.jpg',
            'nama_menu' => 'Pangsit Mie',
            'deskripsi' => 'Pangsit dengan mie dan kuah yang lezat',
            'harga' => 18000,
            'toko_id' => 'berkatkatering@gmail.com',
            'kantin_id' => 2,
        ],
    ];
        DB::table('pe_menu')->insert($foods);
    }
}