<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $foods = [[
            // start menu carnival
            'picture' => 'carnival6.jpeg',
            'nama_menu' => 'French Fries',
            'deskripsi' => 'Kentang goreng dengan bumbu dan saos pilihan',
            'harga' => 16000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival5.jpg',
            'nama_menu' => 'Mushroom Crispy Jumbo',
            'deskripsi' => 'Jamur goreng dengan bumbu dan saos pilihan',
            'harga' => 14000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival8.jpg',
            'nama_menu' => 'Tahu Crispy',
            'deskripsi' => 'Tahu goreng dengan bumbu dan saos pilihan',
            'harga' => 12000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival7.jpg',
            'nama_menu' => 'Kulit Ayam Crispy',
            'deskripsi' => 'Kulit ayam crispy ditaburi bumbu pilihan',
            'harga' => 14000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival4.jpg',
            'nama_menu' => 'Curly Fries',
            'deskripsi' => 'Kentang curly dengan bumbu dan saos pilihan',
            'harga' => 16000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival3.jpg',
            'nama_menu' => 'Chicken Crispy',
            'deskripsi' => 'Potongan ayam goreng crispy ditaburi bumbu lezat',
            'harga' => 17000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival1.jpg',
            'nama_menu' => 'Fish Ball',
            'deskripsi' => 'Bola ikan, isi 10',
            'harga' => 16000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
        ], [
            'picture' => 'carnival2.jpg',
            'nama_menu' => 'Shrimp Ball',
            'deskripsi' => 'Bola udang, isi 8',
            'harga' => 16000,
            'toko_id' => 'carnival@gmail.com',
            'kantin_id' => 3,
            // end menu carnival
        ],     [
            // start menu japanesefood
            'picture' => 'japanesefood1.jpg',
            'nama_menu' => 'Nasi Goreng Original',
            'deskripsi' => 'Nasi goreng dengan bumbu original',
            'harga' => 18000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood2.jpg',
            'nama_menu' => 'Nasi Goreng Hongkong',
            'deskripsi' => 'Nasi goreng ala Hongkong',
            'harga' => 20000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood3.jpg',
            'nama_menu' => 'Teriyaki',
            'deskripsi' => 'Ayam atau daging panggang dengan saus teriyaki',
            'harga' => 25000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood4.jpg',
            'nama_menu' => 'Yakiniku',
            'deskripsi' => 'Daging panggang ala Jepang',
            'harga' => 28000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood5.jpg',
            'nama_menu' => 'Yakisoba',
            'deskripsi' => 'Mie panggang dengan sayuran dan daging',
            'harga' => 22000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood6.jpeg',
            'nama_menu' => 'Chicken Katsu',
            'deskripsi' => 'Ayam goreng tepung khas Jepang',
            'harga' => 20000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],     [
            'picture' => 'japanesefood7.jpg',
            'nama_menu' => 'Beef Bowl',
            'deskripsi' => 'Donburi dengan daging sapi',
            'harga' => 23000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'japanesefood8.jpg',
            'nama_menu' => 'Sushi',
            'deskripsi' => 'Seleksi sushi yang lezat',
            'harga' => 30000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'japanesefood9.jpg',
            'nama_menu' => 'Ramen',
            'deskripsi' => 'Mie Jepang dalam kuah lezat',
            'harga' => 25000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'japanesefood10.jpg',
            'nama_menu' => 'Chicken Karaage',
            'deskripsi' => 'Ayam goreng ala Jepang',
            'harga' => 22000,
            'toko_id' => 'japanesefood@gmail.com',
            'kantin_id' => 3,
            // end japanese food
        ],
        [
            //start depot kita
            'picture' => 'depotkita1.jpg',
            'nama_menu' => 'Nasi Ayam Goreng',
            'deskripsi' => 'Nasi dengan ayam goreng spesial',
            'harga' => 18000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita2.jpg',
            'nama_menu' => 'Nasi Fu Yung Hai',
            'deskripsi' => 'Nasi dengan telur fu yung hai',
            'harga' => 22000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita3.jpg',
            'nama_menu' => 'Nasi Koloke',
            'deskripsi' => 'Nasi dengan campuran kol dan bakso',
            'harga' => 20000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita4.jpg',
            'nama_menu' => 'Nasi Campur',
            'deskripsi' => 'Nasi dengan berbagai macam lauk',
            'harga' => 25000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita5.jpg',
            'nama_menu' => 'Nasi Ayam Geprek',
            'deskripsi' => 'Nasi dengan ayam geprek yang pedas',
            'harga' => 21000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita6.jpg',
            'nama_menu' => 'Es Soda Gembira',
            'deskripsi' => 'Minuman segar dengan soda dan sirup',
            'harga' => 8000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotkita8.jpg',
            'nama_menu' => 'Milo',
            'deskripsi' => 'Minuman coklat bubuk Milo',
            'harga' => 10000,
            'toko_id' => 'depotkita@gmail.com',
            'kantin_id' => 3,
            // end depot kita
        ],
        [
            // start depot mapan
            'picture' => 'depotmapan1.jpg',
            'nama_menu' => 'Nasi Goreng Telur',
            'deskripsi' => 'Nasi goreng dengan telur',
            'harga' => 15000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan2.jpg',
            'nama_menu' => 'Nasi Campur',
            'deskripsi' => 'Nasi dengan berbagai macam lauk',
            'harga' => 18000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan3.jpg',
            'nama_menu' => 'Nasi Ayam Koloke',
            'deskripsi' => 'Nasi dengan ayam dan koloke',
            'harga' => 20000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan4.jpg',
            'nama_menu' => 'Nasi Capcay',
            'deskripsi' => 'Nasi dengan campuran sayuran dan daging',
            'harga' => 22000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan5.jpg',
            'nama_menu' => 'Es Teh',
            'deskripsi' => 'Minuman teh dingin',
            'harga' => 5000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmapan6.jpg',
            'nama_menu' => 'Es Jeruk',
            'deskripsi' => 'Minuman jeruk segar',
            'harga' => 6000,
            'toko_id' => 'depotmapan@gmail.com',
            'kantin_id' => 3,
            //end depot mapan
        ],
        [
            //start kuenyonya
            'picture' => 'kuenyonya1.jpg',
            'nama_menu' => 'Lemper',
            'deskripsi' => '4pcs Makanan tradisional berisi ketan dan daging',
            'harga' => 12000,
            'toko_id' => 'kuenyonya@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kuenyonya2.jpg',
            'nama_menu' => 'Kue Nyonya',
            'deskripsi' => '2pcs Kue tradisional khas Nyonya',
            'harga' => 10000,
            'toko_id' => 'kuenyonya@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kuenyonya3.jpg',
            'nama_menu' => 'Kue Ambon',
            'deskripsi' => '3pcs Kue tradisional khas Ambon',
            'harga' => 15000,
            'toko_id' => 'kuenyonya@gmail.com',
            'kantin_id' => 3,
            //end kuenyonya
        ],
        [
            // start sotoayamjago
            'picture' => 'sotoayamjago1.jpg',
            'nama_menu' => 'Soto Ayam Telur',
            'deskripsi' => 'Soto ayam dengan tambahan telur',
            'harga' => 12000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago2.jpg',
            'nama_menu' => 'Soto Ayam Spesial',
            'deskripsi' => 'Soto ayam spesial dengan bumbu istimewa',
            'harga' => 15000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago3.jpeg',
            'nama_menu' => 'Soto Ayam Jago',
            'deskripsi' => 'Soto ayam khas dengan cita rasa yang unik',
            'harga' => 18000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago4.jpg',
            'nama_menu' => 'Soto Ayam',
            'deskripsi' => 'Soto ayam dengan kuah yang lezat',
            'harga' => 13000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago5.jpg',
            'nama_menu' => 'Soto Ayam Campur',
            'deskripsi' => 'Soto ayam dengan campuran berbagai bahan',
            'harga' => 16000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago6.jpg',
            'nama_menu' => 'Nasi Putih',
            'deskripsi' => 'Nasi putih yang lembut',
            'harga' => 5000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago7.jpg',
            'nama_menu' => 'Lontong',
            'deskripsi' => 'Lontong sebagai pelengkap hidangan',
            'harga' => 3000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'sotoayamjago8.jpg',
            'nama_menu' => 'Es Teh Manis',
            'deskripsi' => 'Minuman teh manis yang segar',
            'harga' => 6000,
            'toko_id' => 'sotoayamjago@gmail.com',
            'kantin_id' => 3,
            // end soto ayam jago
        ],
        [
            // start ndokee
            'picture' => 'ndokee1.jpeg',
            'nama_menu' => 'Nasi Goreng Ayam',
            'deskripsi' => 'Nasi goreng dengan potongan ayam yang lezat',
            'harga' => 12000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee2.jpg',
            'nama_menu' => 'Nasi Koloke',
            'deskripsi' => 'Nasi dengan campuran daging dan sayuran',
            'harga' => 10000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee3.jpg',
            'nama_menu' => 'Ayam Lada Hitam',
            'deskripsi' => 'Ayam dengan saus lada hitam yang pedas',
            'harga' => 15000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee4.jpg',
            'nama_menu' => 'Fu Yung Hai',
            'deskripsi' => 'Telur dadar dengan berbagai bahan',
            'harga' => 8000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee5.jpg',
            'nama_menu' => 'Telur Kornet',
            'deskripsi' => 'Telur dengan kornet yang gurih',
            'harga' => 9000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee6.jpeg',
            'nama_menu' => 'Cap Jay',
            'deskripsi' => 'Sayuran dengan campuran daging',
            'harga' => 11000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee7.jpg',
            'nama_menu' => 'Ayam Jamur',
            'deskripsi' => 'Ayam dengan saus jamur yang lezat',
            'harga' => 13000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ndokee8.jpg',
            'nama_menu' => 'Bakmie Goreng Ayam',
            'deskripsi' => 'Mie goreng dengan potongan ayam',
            'harga' => 14000,
            'toko_id' => 'ndokee@gmail.com',
            'kantin_id' => 3,
            // end ndokee
        ],
        [
            'picture' => 'kedaihong1.jpg',
            'nama_menu' => 'Nasi Ayam Kremus',
            'deskripsi' => 'Nasi dengan ayam bumbu kremus yang lezat',
            'harga' => 16000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kedaihong2.jpg',
            'nama_menu' => 'Nasi Ayam Bakar',
            'deskripsi' => 'Nasi dengan ayam bakar yang harum',
            'harga' => 18000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kedaihong3.jpg',
            'nama_menu' => 'Nasi Ayam Bumbu Rujak',
            'deskripsi' => 'Nasi dengan ayam bumbu rujak yang segar',
            'harga' => 15000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kedaihong4.jpg',
            'nama_menu' => 'Nasi Ayam Penyet',
            'deskripsi' => 'Nasi dengan ayam penyet yang pedas',
            'harga' => 17000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kedaihong5.jpeg',
            'nama_menu' => 'Tahu Tek',
            'deskripsi' => 'Tahu dengan saus kacang khas Tahu Tek',
            'harga' => 12000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kedaihong6.jpg',
            'nama_menu' => 'Indomie',
            'deskripsi' => 'Mie instan dengan berbagai pilihan rasa',
            'harga' => 8000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kedaihong7.jpg',
            'nama_menu' => 'Es Teh',
            'deskripsi' => 'Minuman teh manis yang segar',
            'harga' => 5000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kedaihong8.jpeg',
            'nama_menu' => 'Es Jeruk',
            'deskripsi' => 'Minuman jeruk segar',
            'harga' => 6000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'kedaihong9.jpg',
            'nama_menu' => 'Cappucino',
            'deskripsi' => 'Kopi dengan foam susu lembut',
            'harga' => 10000,
            'toko_id' => 'kedaihong@gmail.com',
            'kantin_id' => 3,
             // end hong
        ],
        [
            'picture' => 'depotmie551.jpg',
            'nama_menu' => 'Pangsit Kuah',
            'deskripsi' => 'Pangsit dengan kuah yang lezat',
            'harga' => 12000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmie552.jpg',
            'nama_menu' => 'Mie Bakso',
            'deskripsi' => 'Mie dengan bakso yang kenyal',
            'harga' => 15000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmie553.jpeg',
            'nama_menu' => 'Mie Goreng Jamur',
            'deskripsi' => 'Mie goreng dengan jamur yang lezat',
            'harga' => 13000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmie554.jpg',
            'nama_menu' => 'Mie Goreng Special',
            'deskripsi' => 'Mie goreng dengan berbagai bahan spesial',
            'harga' => 16000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmie555.jpg',
            'nama_menu' => 'Mie Cap Jay Goreng/Kuah',
            'deskripsi' => 'Mie Cap Jay goreng atau dengan kuah',
            'harga' => 14000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmie556.jpg',
            'nama_menu' => 'Ayam Penyet',
            'deskripsi' => 'Ayam penyet dengan sambal pedas',
            'harga' => 17000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmie557.jpg',
            'nama_menu' => 'Ayam Bakar',
            'deskripsi' => 'Ayam bakar dengan bumbu khas',
            'harga' => 18000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmie558.jpeg',
            'nama_menu' => 'Telor Ceplok',
            'deskripsi' => 'Telur ceplok dengan bumbu',
            'harga' => 8000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmie559.jpg',
            'nama_menu' => 'Sate Ayam',
            'deskripsi' => 'Sate ayam dengan bumbu kacang',
            'harga' => 12000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'depotmie5510.jpg',
            'nama_menu' => 'Sate Kambing',
            'deskripsi' => 'Sate kambing dengan bumbu kacang',
            'harga' => 15000,
            'toko_id' => 'depotmie55@gmail.com',
            'kantin_id' => 3,
        ],
        // end depot mie
        [
            'picture' => 'ayampinarak1.jpg',
            'nama_menu' => 'Ayam Broiler Utuh',
            'deskripsi' => 'Ayam broiler utuh dengan bumbu khas',
            'harga' => 80000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ayampinarak2.jpeg',
            'nama_menu' => 'Ayam Kampung Utuh',
            'deskripsi' => 'Ayam kampung utuh dengan bumbu tradisional',
            'harga' => 60000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ayampinarak3.jpg',
            'nama_menu' => 'Jamur Crispy',
            'deskripsi' => 'Jamur crispy dengan tepung renyah',
            'harga' => 12000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ayampinarak4.jpg',
            'nama_menu' => 'Tahu Crispy',
            'deskripsi' => 'Tahu crispy dengan tepung renyah',
            'harga' => 10000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'ayampinarak5.jpg',
            'nama_menu' => 'Tahu Tempe',
            'deskripsi' => 'Tahu dan tempe goreng dengan bumbu kacang',
            'harga' => 15000,
            'toko_id' => 'ayampinarak@gmail.com',
            'kantin_id' => 3,
        ],
        // end pinarak
        [
            'picture' => 'pokpok1.jpg',
            'nama_menu' => 'Chicken Popcorn',
            'deskripsi' => 'Potongan ayam kecil yang digoreng garing',
            'harga' => 12000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'pokpok2.jpg',
            'nama_menu' => 'Chicken Skin',
            'deskripsi' => 'Kulit ayam yang digoreng crispy',
            'harga' => 10000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'pokpok3.jpg',
            'nama_menu' => 'Crispy Dory',
            'deskripsi' => 'Daging dory yang digoreng dengan tepung renyah',
            'harga' => 18000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'pokpok4.jpg',
            'nama_menu' => 'Crispy Squid',
            'deskripsi' => 'Cumi-cumi yang digoreng dengan tepung crispy',
            'harga' => 15000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'pokpok5.jpg',
            'nama_menu' => 'Tofu Fries',
            'deskripsi' => 'Tahu yang dipotong seperti kentang goreng',
            'harga' => 13000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'pokpok6.jpg',
            'nama_menu' => 'French Fries',
            'deskripsi' => 'Kentang goreng dengan bentuk panjang',
            'harga' => 10000,
            'toko_id' => 'pokpok@gmail.com',
            'kantin_id' => 3,
        ],
        // end pokpok
        
        [
            'picture' => 'chattime1.jpg',
            'nama_menu' => 'Milk Tea',
            'deskripsi' => 'Minuman teh susu yang lezat',
            'harga' => 12000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime2.jpg',
            'nama_menu' => 'Vanilla Milk Tea',
            'deskripsi' => 'Minuman teh susu dengan rasa vanilla',
            'harga' => 13000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime3.jpg',
            'nama_menu' => 'Hazelnut Milk Tea',
            'deskripsi' => 'Minuman teh susu dengan rasa hazelnut',
            'harga' => 14000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime4.jpg',
            'nama_menu' => 'Mango Green Tea',
            'deskripsi' => 'Minuman mangga hijau dengan aroma melati',
            'harga' => 11000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime5.jpg',
            'nama_menu' => 'Green Tea Latte',
            'deskripsi' => 'Minuman susu dengan teh hijau',
            'harga' => 15000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime6.jpg',
            'nama_menu' => 'Kopi Susu Gula Aren',
            'deskripsi' => 'Kopi dengan susu dan gula aren',
            'harga' => 16000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime7.jpg',
            'nama_menu' => 'Mochacinno',
            'deskripsi' => 'Kopi dengan campuran coklat dan susu',
            'harga' => 17000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime8.jpg',
            'nama_menu' => 'Americano',
            'deskripsi' => 'Kopi hitam tanpa susu',
            'harga' => 10000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime9.jpg',
            'nama_menu' => 'Latte',
            'deskripsi' => 'Espresso dengan susu',
            'harga' => 12000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime10.jpg',
            'nama_menu' => 'Cappuccino',
            'deskripsi' => 'Kopi dengan foam susu lembut',
            'harga' => 14000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime11.jpg',
            'nama_menu' => 'Vanilla Latte',
            'deskripsi' => 'Latte dengan rasa vanilla',
            'harga' => 16000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime12.jpg',
            'nama_menu' => 'Hazelnut Latte',
            'deskripsi' => 'Latte dengan rasa hazelnut',
            'harga' => 16000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime13.jpg',
            'nama_menu' => 'Caramel Latte',
            'deskripsi' => 'Latte dengan rasa karamel',
            'harga' => 17000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime14.jpg',
            'nama_menu' => 'Pure Cocoa',
            'deskripsi' => 'Minuman coklat murni tanpa tambahan susu',
            'harga' => 13000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'chattime15.jpg',
            'nama_menu' => 'Honey Lemon Juice',
            'deskripsi' => 'Minuman lemon dengan tambahan madu',
            'harga' => 12000,
            'toko_id' => 'chattime@gmail.com',
            'kantin_id' => 3,
        ],
        // end chattime
        [
            'picture' => 'starbucks1.jpg',
            'nama_menu' => 'Caramel Macchiato',
            'deskripsi' => 'Espresso dengan susu dan sirup karamel',
            'harga' => 28000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'starbucks2.jpg',
            'nama_menu' => 'Americano',
            'deskripsi' => 'Kopi hitam tanpa susu',
            'harga' => 24000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'starbucks3.jpg',
            'nama_menu' => 'Caffe Mocha',
            'deskripsi' => 'Espresso dengan susu dan saus coklat',
            'harga' => 26000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'starbucks4.jpg',
            'nama_menu' => 'Green Tea Latte',
            'deskripsi' => 'Minuman susu dengan teh hijau',
            'harga' => 25000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'starbucks5.jpg',
            'nama_menu' => 'Matcha Latte',
            'deskripsi' => 'Minuman susu dengan bubuk matcha',
            'harga' => 27000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'starbucks6.jpg',
            'nama_menu' => 'Chocolate Signature',
            'deskripsi' => 'Minuman coklat spesial dengan rasa khas',
            'harga' => 29000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'starbucks7.jpg',
            'nama_menu' => 'Peppermint Mocha',
            'deskripsi' => 'Caffe Mocha dengan rasa mint segar',
            'harga' => 30000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 3,
        ],
        [
            'picture' => 'starbucks8.jpg',
            'nama_menu' => 'Sakura Latte',
            'deskripsi' => 'Minuman susu dengan aroma sakura',
            'harga' => 28000,
            'toko_id' => 'starbucks@gmail.com',
            'kantin_id' => 3,
        ],
        
    ];
        DB::table('pe_menu')->insert($foods);
    }
}